#
# /*
#  * # Copyright 2020 Paychex, Inc.
#  * # Licensed pursuant to the terms of the Apache License, Version 2.0 (the "License");
#  * # your use of the Work is subject to the terms and conditions of the License.
#  * # You may obtain a copy of the License at
#  *
#  * # http://www.apache.org/licenses/LICENSE-2.0
#  *
#  * # Disclaimer of Warranty. Unless required by applicable law or agreed to in writing, Licensor
#  * # provides the Work (and each Contributor provides its Contributions) on an "AS IS" BASIS,
#  * # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied, including,
#  * # without limitation, any warranties or conditions of TITLE, NON-INFRINGEMENT,
#  * # MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE. You are solely responsible
#  * # for determining the appropriateness of using or redistributing the Work and assume
#  * # any risks associated with your exercise of permissions under this License.
#  */
spring:
  config:
    name: local
  data:
    mongodb:
      database: test
      uri: mongodb://mdw20.payx-demo.com:27017
      #uri: mongodb://localhost:30000
      key:
        vault:
          database: "encryption"
          collection: "__keyVault"
          name: "dataEncKey"
      kmsprovider: "local"
      encryption:
        cryptdpath: "/usr/local/bin/mongocryptd"
        #cryptdpath: "/usr/bin/mongocryptd"
        masterKeyPath: "master-key.txt"
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration,org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration,org.springframework.boot.autoconfigure.data.mongo.MongoRepositoriesAutoConfiguration
logging:
  level:
    org.springframework: ERROR
    com.paychex: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file:
    name: app.log
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /api-ui


